import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:octo_image/octo_image.dart';
import 'package:ultimate_bundle/flutima/helpers/constants.dart';
import 'package:ultimate_bundle/premium/barbera/src/helpers/constans.dart';
import 'package:ultimate_bundle/premium/barbera/src/helpers/screens.dart';
import 'package:ultimate_bundle/premium/barbera/src/helpers/toast.dart';
import 'package:ultimate_bundle/premium/barbera/src/mock_data/barber_mock.dart';
import 'package:ultimate_bundle/premium/barbera/src/mock_data/slot_mock.dart';
import 'package:ultimate_bundle/premium/barbera/src/widgets/custom_elevated_button.dart';

part 'screens/schedule_screen.dart';
part 'widgets/build_barber.dart';
part 'widgets/build_date.dart';
part 'widgets/build_sliver_appbar.dart';
part 'widgets/build_slot.dart';
