# name: flutima_remake
name: ultimate_bundle

description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.10.22+22

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  advance_notification: ^1.0.6
  animated_splash_screen: ^1.3.0
  auto_size_text: ^3.0.0-nullsafety.0
  awesome_card: ^1.1.7
  bottom_navy_bar: ^6.0.0
  bottom_sheet: ^3.1.2
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.5
  dot_navigation_bar: ^1.0.1+4
  dots_indicator: ^2.1.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_iconly: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_star: ^1.2.0
  flutter_svg: ^2.0.2
  flutter_swiper_null_safety: ^1.0.2
  fluttertoast: ^8.2.1
  form_field_validator: ^1.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.4
  google_sign_in: ^6.1.4
  icon_badge: ^1.0.0
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  launch_review: ^3.0.1
  lottie: ^2.2.0
  # modal_bottom_sheet: ^2.1.2
  octo_image: ^1.0.2
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  pinput: ^2.2.31
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  readmore: ^2.2.0
  responsive_grid: ^2.1.0
  share: ^2.0.4
  simple_animations: ^4.2.0
  smooth_star_rating:
    git:
      url: https://github.com/educup/smoothratingbar
  syncfusion_flutter_sliders: ^20.4.52
  timeago: ^3.3.0
  timeline_tile: ^2.0.0
  timer_count_down: ^2.2.2
  url_launcher: ^6.1.10
  video_player: ^2.5.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/lotties/
