// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRsZdeuvV9kRRU6K6Gg05F41qlL3RwcLk',
    appId: '1:21352098080:web:b56ee907a2bf8b96f08f45',
    messagingSenderId: '21352098080',
    projectId: 'blooddonor-0935',
    authDomain: 'blooddonor-0935.firebaseapp.com',
    storageBucket: 'blooddonor-0935.appspot.com',
    measurementId: 'G-Y78GG8039H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAkoUi033jhQFmpTfVgf1Sqponzz8oHh0',
    appId: '1:21352098080:android:77f9a7e8d60ba4c5f08f45',
    messagingSenderId: '21352098080',
    projectId: 'blooddonor-0935',
    storageBucket: 'blooddonor-0935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCq7wSJ33zuaPpwHXpKXdn1bbrpYLlJPo',
    appId: '1:21352098080:ios:348787f7ba84bef7f08f45',
    messagingSenderId: '21352098080',
    projectId: 'blooddonor-0935',
    storageBucket: 'blooddonor-0935.appspot.com',
    iosClientId:
        '21352098080-s6954hi3euulroddktej6tk3uni42bi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutimaRemake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCq7wSJ33zuaPpwHXpKXdn1bbrpYLlJPo',
    appId: '1:21352098080:ios:348787f7ba84bef7f08f45',
    messagingSenderId: '21352098080',
    projectId: 'blooddonor-0935',
    storageBucket: 'blooddonor-0935.appspot.com',
    iosClientId:
        '21352098080-s6954hi3euulroddktej6tk3uni42bi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutimaRemake',
  );
}
