import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_feather_icons/flutter_feather_icons.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_swiper_null_safety/flutter_swiper_null_safety.dart';
import 'package:get/get.dart';
import 'package:octo_image/octo_image.dart';
import 'package:share/share.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:ultimate_bundle/flutima/helpers/constants.dart';
import 'package:ultimate_bundle/premium/barbera/src/helpers/constans.dart';
import 'package:ultimate_bundle/premium/barbera/src/helpers/screens.dart';
import 'package:ultimate_bundle/premium/barbera/src/helpers/toast.dart';
import 'package:ultimate_bundle/premium/barbera/src/models/gallery_model.dart';
import 'package:ultimate_bundle/premium/barbera/src/widgets/custom_app_bar.dart';
import 'package:ultimate_bundle/premium/barbera/src/widgets/custom_dots_indicator.dart';

part 'screens/gallery_screen.dart';
part 'widgets/build_more_bottom_sheet.dart';
part 'widgets/build_swiper.dart';
